/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class ExceptionDriverTest {
    @Test public void appHasAGreeting() {
        ExceptionDriver classUnderTest = new ExceptionDriver();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
